name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build contracts
        run: |
          forge --version
          forge build --sizes

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        env:
          MAINNET_RPC_URL: ${{secrets.MAINNET_RPC_URL}}
          OPTIMISM_RPC_URL: ${{secrets.OPTIMISM_RPC_URL}}
          ARBITRUM_ONE_RPC_URL: ${{secrets.ARBITRUM_ONE_RPC_URL}}
          ARBITRUM_NOVA_RPC_URL: ${{secrets.ARBITRUM_NOVA_RPC_URL}}
          GNOSIS_CHAIN_RPC_URL: ${{secrets.GNOSIS_CHAIN_RPC_URL}}
          BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
        run: FOUNDRY_PROFILE=ci forge test
